config/routes.rb
PushvendorPos::Application.routes.draw do
  
  resources :funcionarios

  resources :pedidos

  resources :fornecedors, :path => "fornecedores"

  resources :transportadoras

  resources :homes

  resources :item_categories

  resources :reports, :path => "relatorios" do
    collection do
      get 'total_report'
      get 'date_range_report'
      get 'customer_report'
      get 'item_report'
    end
  end

  resources :line_items

  resources :payments do
    collection do
      get 'make_payment'
    end
  end

  resources :configurations do 
    collection do 
      get 'update'
    end
  end

  resources :customers, :path => "clientes"

  resources :items do
    get 'search'
    collection do
      get 'search'
    end
  end

  resources :sales do
    collection do
      get 'update_line_item_options'
      get 'update_customer_options'
      get 'update_funcionario_options'
      get 'create_line_item'
      get 'update_totals'
      get 'add_item'
      get 'remove_item'
      get 'create_customer_association'
      get 'create_funcionario_association'
      get 'create_custom_item'
      get 'create_custom_customer'
      get 'add_comment'
      post 'override_price'
      post 'sale_discount'
    end
  end

  resources :dashboard do
    collection do
      get 'create_sale_with_product'
    end
  end

  devise_for :usuarios
   devise_scope :usuario do
   authenticated :usuario do
  root 'dashboard#index', as: :authenticated_root
  end
end

  root 'homes#index'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  	@recent_sales = Sale.find(:all, :limit => 10, :order => 'id DESC')
  	@popular_items = Item.find(:all, :limit => 10, :order => 'amount_sold DESC')
  end

  def create_sale_with_product
		@sale = Sale.create
		item = Item.find(params[:item_id])
		LineItem.create(:item_id => params[:item_id].to_i, :quantity => params[:quantity].to_i, :price => item.price, :total_price => item.price * params[:quantity].to_i, :sale_id => @sale.id)
    
		price = (item.price * params[:quantity].to_i )

    @sale.tax = price * get_tax_rate
    @sale.amount = price
    @sale.total_amount = price + (price * get_tax_rate)
    @sale.save

    redirect_to :controller => 'sales', :action => 'edit', :id => @sale.id
	end

	def get_tax_rate
    if @configurations.tax_rate.blank?
      return 0.00
    else
      return @configurations.tax_rate.to_f * 0.01
    end
  end

end

app/views/dashboard/_guest.html.erb
<div class="container">
  
  <%= form_for("usuario", :url => usuario_session_path, :html => { :class => "form-signin" }) do |f| %>
  	<h2 class="form-signin-heading"><a target="_blank" href="http://www.pushvendor.com">PushVendor.com</a></h2>
      <%= f.text_field :email, :class => 'form-control', :placeholder => 'Email Address' %>
      <%= f.password_field :password, :class => 'form-control', :placeholder => 'Password' %>
      <label class="checkbox">
      	<%= f.check_box :remember_me %> Remember me
      </label>
      <%= link_to "Forgot your password?", new_password_path('user') %>
      <button class="btn btn-lg btn-primary btn-block" value="Sign in" type="submit">Sign in</button>
      <p class="copyright">Copyright &copy; 2014 PushVendor</p>
    <% end %>

</div>

app/views/dashboard/_logged_in.html.erb
<%= render :partial => 'template/dashboard_menu' %>

<div class="panel panel-default">
  <div class="panel-heading">Vendas Recentes</div>
  <div class="table-responsive">
	  <table class="table table-striped table-bordered table-hover">
	  	<tr>
	  		<th>#</th>
        <th>Gerado em</th>
        <th>Cliente</th>
        <th>Funcionário</th>
        <th>Total</th>
        <th>Pago</th>
        <th>Balanço</th>
        <th>Ações</th>
	  	</tr>
	  	<% for sale in @recent_sales %>
	    	<tr class="<%= sale.remaining_balance == 0.00 && !sale.total_amount.blank? ? 'success' : '' %>">
	    		<td><%= sale.id %></td>
          <td><%= sale.created_at.strftime("%d/%m/%y %I:%M:%S %p")  %></td>
          <td><%= sale.customer.blank? ? '-' : sale.customer.nome %></td>
          <td><%= sale.funcionario.blank? ? '-' : sale.funcionario.nome %></td>
          <td><%= number_to_currency sale.total_amount, :unit => "R$" %></td>
          <td><%= number_to_currency sale.paid_total, :unit => "R$" %></td>
          <td><%= sale.remaining_balance == 0.00 && sale.payments.count > 0 ? "Pago" : "#{number_to_currency sale.remaining_balance}" %></td>
          <td><%= link_to 'Detalhes', edit_sale_path(sale) %> | <%= link_to 'Excluir', sale, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
	    	</tr>
	    <% end %>
	  </table>
	</div>
</div>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Items Populares</div>

  <div class="panel-body">
    <% for item in @popular_items %>
      <%= link_to create_sale_with_product_dashboard_index_path(:item_id => item.id, :quantity => 1) do %>
      <% if item.stock_amount > 0 && item.amount_sold >= 10 %>
        <button type="button" class="btn btn-default">
          <%= item.name %>
        </button>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>


<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Sumário</div>

  <!-- Table -->
  <%= render :partial => 'template/sales_summary' %>
</div>

app/views/dashboard/index.html.erb
<% if usuario_signed_in? %>
	<%= render :partial => 'logged_in' %>
<% else %>
	<%= render :partial => 'guest' %>
<% end %>