config/routes.rb
PushvendorPos::Application.routes.draw do
  
  resources :funcionarios

  resources :pedidos

  resources :fornecedors, :path => "fornecedores"

  resources :transportadoras

  resources :homes

  resources :item_categories

  resources :reports, :path => "relatorios" do
    collection do
      get 'total_report'
      get 'date_range_report'
      get 'customer_report'
      get 'item_report'
    end
  end

  resources :line_items

  resources :payments do
    collection do
      get 'make_payment'
    end
  end

  resources :configurations do 
    collection do 
      get 'update'
    end
  end

  resources :customers, :path => "clientes"

  resources :items do
    get 'search'
    collection do
      get 'search'
    end
  end

  resources :sales do
    collection do
      get 'update_line_item_options'
      get 'update_customer_options'
      get 'update_funcionario_options'
      get 'create_line_item'
      get 'update_totals'
      get 'add_item'
      get 'remove_item'
      get 'create_customer_association'
      get 'create_funcionario_association'
      get 'create_custom_item'
      get 'create_custom_customer'
      get 'add_comment'
      post 'override_price'
      post 'sale_discount'
    end
  end

  resources :dashboard do
    collection do
      get 'create_sale_with_product'
    end
  end

  devise_for :usuarios
   devise_scope :usuario do
   authenticated :usuario do
  root 'dashboard#index', as: :authenticated_root
  end
end

  root 'homes#index'

end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
  belongs_to :fornecedor

  validates_presence_of :pedido, :email, :fornecedor, :message => "Campo obrigatório"
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{3,})\z/i, on: :create, :message => "Email inválido" }

  default_scope :order => 'created_at ASC'

  def self.search(search)
	  if search
	    where('pedido LIKE ?', "%#{search}%")
	  else
	    scoped
	  end
	end
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :authenticate_usuario!, only: [:index, :show, :edit, :update, :destroy, :new]
  before_action :set_pedido, only: [:show, :edit, :update, :destroy]

  # GET /pedidos
  # GET /pedidos.json
  def index
    @pedidos = Pedido.search(params[:search]).paginate(:per_page => 20, :page => params[:page])
  end

  # GET /pedidos/1
  # GET /pedidos/1.json
  def show
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
  end

  # GET /pedidos/1/edit
  def edit
  end

  # POST /pedidos
  # POST /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)

    respond_to do |format|
      if @pedido.save
        PedidoMailer.pedido_email(@pedido).deliver
        format.html { redirect_to '/pedidos', notice: 'Pedido enviado com sucesso.' }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedidos/1
  # PATCH/PUT /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to '/pedidos', notice: 'Pedido atualizado e enviado com sucesso.' }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1
  # DELETE /pedidos/1.json
  def destroy
    @pedido.destroy
    respond_to do |format|
      format.html { redirect_to pedidos_url, notice: 'Pedido excluido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pedido_params
      params.require(:pedido).permit(:fornecedor_id, :data, :email, :pedido, :observacoes)
    end
end

app/helpers/pedidos_helper.rb
module PedidosHelper
	def error_tag(model, attribute)
		if model.errors.has_key? attribute
			content_tag :div, model.errors[attribute].first,
				:class => 'error_message'
		end
	end
end

app/views/pedidos/_form.html.erb
  <%= form_for(@pedido) do |f| %>
    <% if @pedido.errors.any? %>
    <div id="error_explanation">
    Há erros no formulário, por favor verifique.
    </div>
    <% end %>

  <div class="panel panel-default">
  <div class="panel-heading">Pedido</div>
  <div class="panel-body">
   
    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <label>Fornecedor</label>
          <%= f.collection_select :fornecedor_id, Fornecedor.all, :id, :empresa, {prompt: "Selecione um Fornecedor"}, {class: "form-control"}  %>
          <%= error_tag @pedido, :fornecedor %>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="form-group">
          <label>Data</label>
          <%= f.text_field :data, :class => "datepicker" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <label>Pedido</label>
          <%= f.text_field :pedido, :class => "form-control", :placeholder => "Pedido" %>
          <%= error_tag @pedido, :pedido %>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="form-group">
          <label>Observações</label>
          <%= f.text_area :observacoes, :class => "form-control", :placeholder => "Observações" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <label>Email</label>
          <%= f.text_field :email, :class => "form-control", :placeholder => "exemplo@exemplo.com" %>
          <%= error_tag @pedido, :email %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <%= f.submit 'Enviar', :class => "btn btn-success btn-lg" %>
  </div>
</div>
<% end %>

app/views/pedidos/index.html.erb
<%= form_tag pedidos_path, :method => 'get', :id => "items_search" do %>
  <p>
    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Procurar", :pedido => nil %>
    </div>
      </div>
    </div>
  </p>
<% end %>

<div class="panel panel-default">
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th>Fornecedor</th>
            <th>Data</th>
            <th>Pedido</th>
            <th>Ações</th>
          </tr>
        </thead>

        <tbody>
          <% @pedidos.each do |pedido| %>
              <td><%= pedido.fornecedor.empresa %></td>
              <td><%= pedido.created_at.strftime("%d-%m-%Y")%></td>
              <td><%= pedido.pedido %></td>
              <td><%= link_to 'Detalhes', edit_pedido_path(pedido) %> | <%= link_to 'Excluir', pedido, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="panel-body">
        <%= will_paginate @pedidos, renderer: BootstrapPagination::Rails %>
      </div>
    </div>
  </div>
</div>

    <div class="col-sm-12">
      <%= link_to 'Novo Pedido', new_pedido_path, :class => "btn btn-success btn-lg btn3d" %>
    </div>

app/views/pedidos/new.html.erb
<%= render 'form' %>

app/views/pedidos/show.html.erb
<%= render 'form' %>