config/routes.rb
PushvendorPos::Application.routes.draw do
  
  resources :funcionarios

  resources :pedidos

  resources :fornecedors, :path => "fornecedores"

  resources :transportadoras

  resources :homes

  resources :item_categories

  resources :reports, :path => "relatorios" do
    collection do
      get 'total_report'
      get 'date_range_report'
      get 'customer_report'
      get 'item_report'
    end
  end

  resources :line_items

  resources :payments do
    collection do
      get 'make_payment'
    end
  end

  resources :configurations do 
    collection do 
      get 'update'
    end
  end

  resources :customers, :path => "clientes"

  resources :items do
    get 'search'
    collection do
      get 'search'
    end
  end

  resources :sales do
    collection do
      get 'update_line_item_options'
      get 'update_customer_options'
      get 'update_funcionario_options'
      get 'create_line_item'
      get 'update_totals'
      get 'add_item'
      get 'remove_item'
      get 'create_customer_association'
      get 'create_funcionario_association'
      get 'create_custom_item'
      get 'create_custom_customer'
      get 'add_comment'
      post 'override_price'
      post 'sale_discount'
    end
  end

  resources :dashboard do
    collection do
      get 'create_sale_with_product'
    end
  end

  devise_for :usuarios
   devise_scope :usuario do
   authenticated :usuario do
  root 'dashboard#index', as: :authenticated_root
  end
end

  root 'homes#index'

end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base

	#validates_presence_of :nome, :data_nascimento, :endereco, :cidade, :estado, :cep, :telefone, :admissao, :cargo, :cpf, :identidade, :message => "Campo Obrigatório"
	validates_uniqueness_of :cpf, :message => "Cpf já cadastrado"
	validates_uniqueness_of :identidade, :message => "Identidade já cadastrada"
	#validates_length_of :nome, :endereco, :cidade, :maximum => 50, :message => "Limite de caracteres ultrapassado (max: 50)"
	has_many :sales

	default_scope :order => 'nome ASC'

  def self.search(search)
	  if search
	    where('nome LIKE ?', "%#{search}%")
	  else
	    scoped
	end
  end
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :authenticate_usuario!, only: [:index, :show, :edit, :update, :destroy, :new]
  before_action :set_funcionario, only: [:show, :edit, :update, :destroy]

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    @funcionarios = Funcionario.search(params[:search]).paginate(:per_page => 20, :page => params[:page])
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to '/funcionarios', notice: 'Funcionario cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1
  # PATCH/PUT /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to '/funcionarios', notice: 'Funcionario atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: 'Funcionario excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcionario_params
      params.require(:funcionario).permit(:nome, :endereco, :cidade, :estado, :cep, :telefone, :admissao, :cpf, :identidade, :data_nascimento, :cargo)
    end
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/funcionarios/_form.html.erb
  <%= form_for(@funcionario) do |f| %>
    <% if @funcionario.errors.any? %>
    <div id="error_explanation">
    Há erros no formulário, por favor verifique.
    </div>
    <% end %>

  <div class="panel panel-default">
  <div class="panel-heading">Funcionário</div>
  <div class="panel-body">
   
    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <label>Nome</label>
          <%= f.text_field :nome, :class => "form-control", :placeholder => "Nome do Funcionário" %>
          <%= error_tag @funcionario, :nome%>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="form-group">
          <label>Data de Nascimento</label>
          <%= f.text_field :data_nascimento, :class => "datepicker" %>
          <%= error_tag @funcionario, :data_nascimento%>
        </div>
      </div>
    </div>


    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <label>Endereço</label>
          <%= f.text_field :endereco, :class => "form-control", :placeholder => "Endereço" %>
          <%= error_tag @funcionario, :endereco%>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="form-group">
          <label>Cidade</label>
          <%= f.text_field :cidade, :class => "form-control", :placeholder => "Cidade" %>
          <%= error_tag @funcionario, :cidade%>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <label>Estado</label>
          <%= f.select :estado, (['', 'AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MG', 'MT', 'MS','PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO']), {}, :class => "form-control" %>
          <%= error_tag @funcionario, :estado%>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="form-group">
          <label>Cep</label>
          <%= f.text_field :cep, :class => "campo_cep form-control", :placeholder => "99.999-999" %>
          <%= error_tag @funcionario, :cep%>
        </div>
      </div>
      

    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <label>Telefone</label>
          <%= f.text_field :telefone, :class => "campo_telefone form-control", :placeholder => "(99) 9999-9999" %>
          <%= error_tag @funcionario, :telefone%>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="form-group">
          <label>Admissão</label>
          <%= f.text_field :admissao, :class => "datepicker" %>
          <%= error_tag @funcionario, :admissao%>
        </div>
      </div>

      <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <label>Cargo</label>
          <%= f.select :cargo, (["", "Diretor", "Gerente", "Vendedor", "Analista"]), {}, :class => 'form-control' %>
          <%= error_tag @funcionario, :cargo%>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="form-group">
          <label>Cpf</label>
          <%= f.text_field :cpf, :class => "campo_cpf form-control", :placeholder => "999.999.999.99" %>
          <%= error_tag @funcionario, :cpf%>
        </div>
      </div>
      <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <label>Identidade</label>
          <%= f.text_field :identidade, :class => "campo_identidade form-control", :placeholder => "99.999.999.9" %>
          <%= error_tag @funcionario, :identidade%>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <%= f.submit 'Cadastrar', :class => "btn btn-success btn-lg" %>
  </div>
</div>
<% end %>

app/views/funcionarios/edit.html.erb
<%= render 'form' %>

app/views/funcionarios/index.html.erb
<%= form_tag funcionarios_path, :method => 'get', :id => "items_search" do %>
  <p>
    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Procurar", :nome => nil %>
    </div>
      </div>
    </div>
  </p>
<% end %>

<div class="panel panel-default">
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th>Nome</th>
            <th>Cargo</th> 
            <th>Cidade</th>
            <th>Admissão</th>
            <th>Ações</th>
          </tr>
        </thead>

        <tbody>
          <% @funcionarios.each do |funcionario| %>
              <td><%= funcionario.nome %></td>
              <td><%= funcionario.cargo %></td>
              <td><%= funcionario.cidade %></td>
              <td><%= funcionario.admissao %></td>            
              <td><%= link_to 'Detalhes', edit_funcionario_path(funcionario) %> | <%= link_to 'Excluir', funcionario, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="panel-body">
        <%= will_paginate @funcionarios, renderer: BootstrapPagination::Rails %>
      </div>
    </div>
  </div>
</div>

    <div class="col-sm-12">
      <%= link_to 'Novo Funcionário', new_funcionario_path, :class => "btn btn-success btn-lg btn3d" %>
    </div>

app/views/funcionarios/new.html.erb
<%= render 'form' %>

app/views/funcionarios/show.html.erb
<%= render 'form'%>